import { useState } from "react";
import Head from "next/head";
import Image from "next/image";

import { GameBoard } from "../pages/api/getStepTwo";
import Button from "../components/button";

export default function Home() {
  const [gameBoard, setGameBoard] = useState<GameBoard>({
    nextPassage:
      "You don't know what happend.  You remember falling asleep in your bed, your mom tucking you in tighly under your covers.  But now you're far away from home, you can just feel it.  And this room is dark, and unfamiliar.",
    currentTurn: 0,
    userActions: ["Figure out your next step"],
    storySummary: [
      "Turn 1: you remember going to bed at home, but you wake up in a dark unfamiliar room.",
    ],
    nextPassageSummary: [],
    gameOver: false,
    gameStatus: "playing",
  });
  const [loading, setLoading] = useState(false);

  //make a request to the getStep endpoint
  const makeRequest = async (choice: string) => {
    //create a post request with the choice in the body
    setLoading(true);
    const response = await fetch("/api/getStepTwo", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        userChoice: choice,
        previousGameBoard: gameBoard,
      }),
    });
    const { data } = await response.json();
    setGameBoard(data);
    setLoading(false);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className="bg-center bg-cover h-[calc(100vh-200px)] w-full relative z-20"
        style={{ minHeight: "-webkit-fill-available" }}
      >
        <div className="h-screen flex flex-col">
          {/*@ts-ignore*/}
          <img src="/flurish.svg" className="pt-8 px-8 opacity-90" />
          <div className="flex justify-between flex-col flex-grow h-full overflow-hidden">
            {/*Main Content Window*/}
            <div
              className={`max-h-full z-20 relative overflow-scroll h-[calc(100vh-200px)] flex justify-between flex-col transform transition-transform duration-300 bg-black  ${
                loading && " translate-x-full"
              }`}
            >
              {/*Game Text*/}
              <div className="p-8">
                <p className="text-gray-50 font-custom text-lg leading-8 font-light">
                  {gameBoard?.nextPassage}
                </p>
              </div>

              {/*Buttons*/}
              <div className="text-center w-full flex flex-col gap-4 p-8">
                {gameBoard?.gameStatus === "captured" && (
                  <div>
                    <p className="text-gray-900 mt-8 text-lg leading-8 font-light">
                      You&apos;ve been Captured by the Ghosts!
                    </p>
                  </div>
                )}
                {gameBoard?.gameStatus === "victory" && (
                  <div>
                    <p className="text-gray-900 mt-8 text-lg leading-8 font-light">
                      You&apos;ve Escaped the Manor!
                    </p>
                  </div>
                )}
                {gameBoard?.gameStatus === "playing" &&
                  gameBoard?.userActions.map((action) => (
                    <Button
                      key={action}
                      label={action}
                      clickHandler={() => makeRequest(action)}
                      active={!loading}
                    />
                  ))}
              </div>
            </div>

            <div className="absolute top-1/4 z-10 w-full">
              <img
                src="/pencil-draw.gif"
                className="w-48 h-48 invert mx-auto"
              />
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
