import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>
          The Mysterious Montclair Manor: An Interactive Adventure Story
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-center bg-cover w-full h-screen min-h-full relative z-20">
        <div className="pt-24 w-full text-center">
          <h1 className=" text-gray-100" style={{ textShadow: "2px 2px #000" }}>
            <span className="text-2xl block font-custom ">The Mysterious</span>
            <span className="font-custom text-5xl block">Montclair Manor</span>
            <span
              className="text-md italic block text-gray-300"
              style={{ textShadow: "2px 2px #000" }}
            >
              An Interactive Adventure Story
            </span>
          </h1>
        </div>

        <div className="text-center w-full absolute bottom-32">
          <Link href="/game">
            <button className="bg-gray-400 p-1 rounded-sm text-xl">
              <div className="py-2 px-4 relative overflow-hidden bg-gray-100 font-custom text-gray-900">
                <div className="w-4 h-4 rounded-full  absolute -top-2 -left-2 bg-gray-400 z-10" />
                <div className="w-4 h-4 rounded-full  absolute -bottom-2 -left-2 bg-gray-400 z-10" />
                <div className="w-4 h-4 rounded-full  absolute -bottom-2 -right-2 bg-gray-400 z-10" />
                <div className="w-4 h-4 rounded-full  absolute -top-2 -right-2 bg-gray-400 z-10" />
                Start the Adventure
              </div>
            </button>
          </Link>
        </div>
      </main>
      <Image
        src="/castle.png"
        className=" overflow-clip saturate-[15%] relative z-10 opacity-50"
        layout="fill"
        objectFit="cover"
        objectPosition="center"
        alt="bg image"
      />
    </>
  );
}
