import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-center bg-cover h-screen w-full min-h-full relative z-20">
        <div className="bottom-[25%] text-center absolute w-full h-12">
          <Link href="/game">
            <button className="bg-fuchsia-900 text-white text-xl p-4">
              Start Your Nightmare
            </button>
          </Link>
        </div>
      </main>
      <Image
        src="/castle.png"
        className=" overflow-clip saturate-[15%] relative z-10"
        layout="fill"
        objectFit="cover"
        objectPosition="center"
        alt="bg image"
      />
    </>
  );
}
